### ISSUE TITLE
qemu-aarch64-static0: unable to find CPU model 'cortex-a76'

### ISSUE THREAD

**Issue by wrljet** [pguyot/arm-runner-action#90]
Is there a way for this to include a newer (or patched) qemu to support cortex-a76, such as found in Raspberry Pi 5?

```
++ sudo chroot /home/actions/temp/arm-runner/mnt /bin/sh -c 'command -v /bin/sh'
qemu-aarch64-static0: unable to find CPU model 'cortex-a76'
```

See: [this qemu patch](https://lore.kernel.org/all/20231126231210.112820-1-gshan@redhat.com/T/)

Thanks for any assistance,
Bill

**Comment by bvobart** [comment]
Going by https://github.com/pguyot/arm-runner-action/blob/98b8d5a3228f504a8bd54913ab1e23d70f369c6e/action.yml#L102-L127 it seems that you could input this yourself through the `cpu` parameter for this action, provided that the latest version of QEMU bundled with Ubuntu 22.04 (currently the default image used by this action) supports it.

**Comment by pguyot** [comment]
Exactly. This can be achieved by:
- using a container or runner that has an apt package with the qemu patch and installing them, so that:
`apt install -y qemu qemu-user-static`
doesn't overwrite the patched qemu version
- passing cpu parameter.

Question is: what is the use case where exactly emulating the Raspberry Pi 5 CPU makes sense. Is it worth the effort and the longer CI time?

**Comment by pguyot** [comment]
Ubuntu 22.04 indeed features a rather old version of qemu.
You can upgrade to 24.04 once PR #111 is merged, and then you will be able to pass cortex-a76 in `cpu` option.
